export const USER_SET_SIGNED_IN = 'USER_SET_SIGNED_IN';
export const USER_SET_SIGNED_OUT = 'USER_SET_SIGNED_OUT';
export const USER_START_SIGN_OUT = 'USER_START_SIGN_OUT';
export const USER_SIGN_OUT_FAIL = 'USER_SIGN_OUT_FAIL';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const POST_USER_DATA = 'POST_USER_DATA';
export const ADD_USER_AND_DATA = 'ADD_USER_AND_DATA';

export const FETCH_SHALLOW_SUBJECTS = 'FETCH_SHALLOW_SUBJECTS';
export const FETCH_SHALLOW_SUBJECTS_SUCCESS = 'FETCH_SHALLOW_SUBJECTS_SUCCESS';
export const FETCH_SHALLOW_SUBJECTS_FAIL = 'FETCH_SHALLOW_SUBJECTS_FAIL';

export const REMOVE_SUBJECT_LOCALLY = 'REMOVE_SUBJECT_LOCALLY';
export const ADD_SUBJECT_LOCALLY = 'ADD_SUBJECT_LOCALLY';
export const UPDATE_SUBJECT_LOCALLY = 'UPDATE_SUBJECT_LOCALLY';

export const FETCH_TASKS = 'FETCH_TASKS';
export const REFRESH_TASKS = 'REFRESH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const SET_TASKS_LOCALLY = 'SET_TASKS_LOCALLY';
export const CHECK_TASK = 'CHECK_TASK';
export const UNCHECK_TASK = 'UNCHECK_TASK';
export const DATA_SET_ERROR = 'DATA_SET_ERROR';

export const FETCH_EXAMS = 'FETCH_EXAMS';
export const REFRESH_EXAMS = 'REFRESH_EXAMS';
export const FETCH_EXAMS_SUCCESS = 'FETCH_EXAMS_SUCCESS';
export const FETCH_EXAMS_FAIL = 'FETCH_EXAMS_FAIL';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const REFRESH_EVENTS = 'REFRESH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';

export const SET_USER_PREFERENCE = 'SET_USER_PREFERENCE';
export const SET_USER_PREFERENCE_FAIL = 'SET_USER_PREFERENCE_FAIL';

export const FORCE_REFRESH = 'FORCE_REFRESH';