export const USER_SET_SIGNED_IN = 'USER_SET_SIGNED_IN';
export const USER_SET_SIGNED_OUT = 'USER_SET_SIGNED_OUT';
export const USER_START_SIGN_OUT = 'USER_START_SIGN_OUT';
export const USER_SIGN_OUT_FAIL = 'USER_SIGN_OUT_FAIL';

export const FETCH_SHALLOW_SUBJECTS = 'FETCH_SHALLOW_SUBJECTS';
export const FETCH_SHALLOW_SUBJECTS_SUCCESS = 'FETCH_SHALLOW_SUBJECTS_SUCCESS';
export const FETCH_SHALLOW_SUBJECTS_FAIL = 'FETCH_SHALLOW_SUBJECTS_FAIL';

export const REMOVE_SUBJECT_LOCALLY = 'REMOVE_SUBJECT_LOCALLY';
export const ADD_SUBJECT_LOCALLY = 'ADD_SUBJECT_LOCALLY';
export const UPDATE_SUBJECT_LOCALLY = 'UPDATE_SUBJECT_LOCALLY';