export {
    setSpace,
    fetchSpaces,
    fetchSpacesFail,
    fetchSpacesSuccess,
    addSpaceLocally,
    removeSpaceLocally,
    alterSpaceLocally,
    setSignedIn,
    setSignedOut,
    startSignOut,
    signOutFail,
    fetchShallowSubjects,
    fetchShallowSubjectsSuccess,
    fetchShallowSubjectsFail,
    removeSubjectLocally,
    addSubjectLocally,
    setUserData,
    fetchUserData,
    postUserData,
    addUserAndData,
    setUserPreference,
    setUserPreferenceFail,
} from './user';
export {
    fetchTasks,
    refreshTasks,
    fetchTasksSuccess,
    fetchTasksFail,
    dataSetError,
    setTasksLocally,
    checkTask,
    uncheckTask,
    fetchExams,
    refreshExams,
    fetchExamsSuccess,
    fetchExamsFail,
    fetchEvents,
    refreshEvents,
    fetchEventsSuccess,
    fetchEventsFail,
    forceRefresh,
    addAndSaveNewTask,
    addAndSaveNewTaskSuccess,
    addAndSaveNewTaskFail,
} from './data';
export {
    setScrollContainerRef,
} from './general';