name: Build and Deploy to Firebase Hosting
on:
  push:
    branches: 
      - production
        
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Add firebase config
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ./src/firebase/firebaseConfig.json
          FILE_DATA: ${{ secrets.FIREBASE_CONFIG }}
      - name: Add .firebaserc
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: .firebaserc
          FILE_DATA: ${{ secrets.FIREBASERC }}
      - name: Add firebase.json
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: firebase.json
          FILE_DATA: ${{ secrets.FIREBASE_JSON }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
